language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-5-1.gemfile
  - gemfiles/rails-5-2.gemfile
  - gemfiles/rails-6-0.gemfile
script:
  - bundle exec rake spec
matrix:
  exclude:
  # rails 6 requires ruby >= 2.5
  - rvm: 2.4
    gemfile: gemfiles/rails-6-0.gemfile
